package view;



/**
 *
 * @author Martin
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {
     
    /**
     * Creates new form jFrmMenu
     */
    public ViewMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuContenedor = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRubro = new javax.swing.JMenuItem();
        jMenuItemNombre = new javax.swing.JMenuItem();
        jMenuItemPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu gestion");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jMenu1.setText("Administracion");

        jMenuItemProducto.setText("Productos");
        jMenuItemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProducto);

        jMenuContenedor.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItemRubro.setText("Por Rubro");
        jMenuItemRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRubro);

        jMenuItemNombre.setText("Por Nombre");
        jMenuItemNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNombre);

        jMenuItemPrecio.setText("Por Precio");
        jMenuItemPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPrecio);

        jMenuContenedor.add(jMenu2);

        setJMenuBar(jMenuContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductoActionPerformed
        controller.CtrlViewMenuPrincipal.jMenuItemProductoActionPerformed();
    }//GEN-LAST:event_jMenuItemProductoActionPerformed

    private void jMenuItemNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNombreActionPerformed
        controller.CtrlViewMenuPrincipal.jMenuItemNombreActionPerformed();
    }//GEN-LAST:event_jMenuItemNombreActionPerformed

    private void jMenuItemRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRubroActionPerformed
       controller.CtrlViewMenuPrincipal.jMenuItemRubroActionPerformed();
    }//GEN-LAST:event_jMenuItemRubroActionPerformed

    private void jMenuItemPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrecioActionPerformed
         controller.CtrlViewMenuPrincipal.jMenuItemPrecioActionPerformed();
    }//GEN-LAST:event_jMenuItemPrecioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuContenedor;
    private javax.swing.JMenuItem jMenuItemNombre;
    private javax.swing.JMenuItem jMenuItemPrecio;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemRubro;
    // End of variables declaration//GEN-END:variables
}
