package view;

import controller.CtrlGestionProducto;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Martin
 */
public class ViewGestionProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form jFiGestionProducto
     */
    public ViewGestionProducto() {
        initComponents();
        controller.CtrlGestionProducto.CargarInstancia(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPnlContenedor = new javax.swing.JPanel();
        jPnlTxtFiel = new javax.swing.JPanel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtPrecio = new javax.swing.JTextField();
        jCBxRubro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtStock = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jPnlBotones = new javax.swing.JPanel();
        jBtnEditar = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnNuevo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Productos");
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/scaneer.png"))); // NOI18N

        jPnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        jPnlTxtFiel.setBackground(new java.awt.Color(255, 255, 255));

        jTxtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTxtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jTxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripcion");

        jTxtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTxtDescripcion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio");

        jTxtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jTxtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jTxtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPrecioFocusGained(evt);
            }
        });
        jTxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPrecioKeyTyped(evt);
            }
        });

        jCBxRubro.setBackground(new java.awt.Color(255, 255, 255));
        jCBxRubro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCBxRubro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Stock");

        jTxtStock.setBackground(new java.awt.Color(255, 255, 255));
        jTxtStock.setForeground(new java.awt.Color(0, 0, 0));
        jTxtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtStockKeyTyped(evt);
            }
        });

        jBtnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/search2-64.png"))); // NOI18N
        jBtnBuscar.setToolTipText("Nuevo");
        jBtnBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnBuscar.setFocusPainted(false);
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlTxtFielLayout = new javax.swing.GroupLayout(jPnlTxtFiel);
        jPnlTxtFiel.setLayout(jPnlTxtFielLayout);
        jPnlTxtFielLayout.setHorizontalGroup(
            jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnBuscar))
                    .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                        .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jCBxRubro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPnlTxtFielLayout.setVerticalGroup(
            jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlTxtFielLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCBxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlTxtFielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        jBtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/save64.png"))); // NOI18N
        jBtnEditar.setToolTipText("Editar");
        jBtnEditar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnEditar.setFocusPainted(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnBorrar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/clear64.png"))); // NOI18N
        jBtnBorrar.setToolTipText(""); // NOI18N
        jBtnBorrar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnBorrar.setFocusPainted(false);
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        jBtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/log_logout_door_1563.png"))); // NOI18N
        jBtnSalir.setToolTipText("Salir");
        jBtnSalir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnSalir.setFocusPainted(false);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnReset.setBackground(new java.awt.Color(255, 255, 255));
        jBtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/reset.png"))); // NOI18N
        jBtnReset.setToolTipText("Reset");
        jBtnReset.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnReset.setFocusPainted(false);
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconos/new64.png"))); // NOI18N
        jBtnNuevo.setToolTipText("Nuevo");
        jBtnNuevo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jBtnNuevo.setFocusPainted(false);
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotonesLayout = new javax.swing.GroupLayout(jPnlBotones);
        jPnlBotones.setLayout(jPnlBotonesLayout);
        jPnlBotonesLayout.setHorizontalGroup(
            jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlBotonesLayout.setVerticalGroup(
            jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(jPnlBotonesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPnlContenedorLayout = new javax.swing.GroupLayout(jPnlContenedor);
        jPnlContenedor.setLayout(jPnlContenedorLayout);
        jPnlContenedorLayout.setHorizontalGroup(
            jPnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlContenedorLayout.createSequentialGroup()
                        .addComponent(jPnlTxtFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76))
                    .addComponent(jPnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnlContenedorLayout.setVerticalGroup(
            jPnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlTxtFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jPnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        controller.CtrlGestionProducto.btnBuscarXCodigo();
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        controller.CtrlGestionProducto.btnEditarXProducto();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        controller.CtrlGestionProducto.btnBorrar();
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        controller.CtrlGestionProducto.btncerrar();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        controller.CtrlGestionProducto.btnReset();
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        controller.CtrlGestionProducto.botonNuevoProducto();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jTxtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtStockKeyTyped
        controller.CtrlGestionProducto.jTxtStockKeyTyped(evt);
    }//GEN-LAST:event_jTxtStockKeyTyped

    private void jTxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoKeyTyped
        controller.CtrlGestionProducto.jTxtCodigoKeyTyped(evt);
    }//GEN-LAST:event_jTxtCodigoKeyTyped

    private void jTxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPrecioKeyTyped
        controller.CtrlGestionProducto.jTxtPrecioKeyTyped(evt);
    }//GEN-LAST:event_jTxtPrecioKeyTyped

    private void jTxtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPrecioFocusGained
        controller.CtrlGestionProducto.jCBxRubroFocusGained();
    }//GEN-LAST:event_jTxtPrecioFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<String> jCBxRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlBotones;
    private javax.swing.JPanel jPnlContenedor;
    private javax.swing.JPanel jPnlTxtFiel;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescripcion;
    private javax.swing.JTextField jTxtPrecio;
    private javax.swing.JTextField jTxtStock;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getjCBxRubro() {
        return jCBxRubro;
    }

    public JPanel getjPnlTxtFiel() {
        return jPnlTxtFiel;
    }

    public JTextField getjTxtCodigo() {
        return jTxtCodigo;
    }

    public JTextField getjTxtDescripcion() {
        return jTxtDescripcion;
    }

    public JTextField getjTxtPrecio() {
        return jTxtPrecio;
    }

    public JTextField getjTxtStock() {
        return jTxtStock;
    }

    public JButton getjBtnBorrar() {
        return jBtnBorrar;
    }

    public JButton getjBtnEditar() {
        return jBtnEditar;
    }

    public JButton getjBtnNuevo() {
        return jBtnNuevo;
    }

}
